### ISSUE TITLE
Add Morph Explorer support

### ISSUE THREAD

**Issue by Exkywor** [Mgamerz/ME3Explorer#287]
**Is your feature request related to a problem? Please describe.**
In order to get the meshes of NPCs that use head morphs we have to use the Morph Exporter tool, but that only works for the ancient 3.0.1 version of ME3Explorer.

**Describe the solution you'd like**
It would be fantastic to either integrate the tool into the toolset or make it so Morph Exporter can work with LEX.

**Comment by Mgamerz** [comment]
Where is this tool located in the old toolset?

**Comment by Exkywor** [comment]
The tool itself is not part of the old toolset, but to work it requires to be in the same folder as the toolset. I got the file from Jenya who found it somewhere online.
I think this should be the page for it: [https://github.com/gabbyh/MEHeadMorphExporter](https://github.com/gabbyh/MEHeadMorphExporter)

**Comment by henbagle** [comment]
It appears as though the most difficult part of integrating this project would be the export to FBX, as at the moment we don't have the original source for the FBX library used. 

Is the FBX format required for your use case? Or would one of the mesh formats that the toolset can already export work?

**Comment by Mgamerz** [comment]
I linked the original issue I made on their repo to this issue. https://github.com/gabbyh/MEHeadMorphExporter/issues/1

**Comment by henbagle** [comment]
As of the latest nightly (311f5ecfe), there is an experiment to export a selected BioMorphFace to PSK in Package Editor (Under the HenBagle's stuff that saved 5 minutes section). UModel must be installed for this to work.

There seems to be an issue with normals that still needs to be worked out, and obviously this can be better integrated into the toolset in the future.

**Comment by Mgamerz** [comment]
I'm marking this as completed for now, as it is integrated into the toolset. I think a new issue can be opened if we want to try to improve support.
