### ISSUE TITLE
2DAs broken in Legendary Explorer Nightly

### ISSUE THREAD

**Issue by Knighthawk1895** [Mgamerz/ME3Explorer#297]
**Describe the bug**
The 2DA viewer in the Nightly Legendary Explorer release no longer displays the cells of the array properly. Nor can the 2DA be exported to excel (excel shows the same empty cells as LEX).

**To Reproduce**
1. Open the 6.0 Nightly 11/28/2021 release for Legendary Explorer
2. Open Package Editor
3. Open a file with a 2DA in it such as Engine.pcc in LE1
4. Scroll down to one of the 2DAs such as BIOG_2DA_Characters_X.Characters_Character
5. Go to the 2DA tab
6. Observe the empty cells

**Expected behavior**
The 2DA should be displayed like a spreadsheet with row and column headers. However, now only the row headers are visible and every row is a single empty cell. The Binary Interpreter still contains the correct data.

**Screenshots and files used to replicate this**
![2DA Issue](https://user-images.githubusercontent.com/95185489/143781175-ebcfbec9-260e-41a0-8864-0956f619be1d.PNG)
(Mass Effect Legendary Edition\Game\ME1\BioGame\CookedPCConsole\Engine.pcc)

**Version information:**
6.0 Nightly 11/28/2021

**Stack trace**
N/A

**Other information**
N/A

**Comment by Mgamerz** [comment]
Still working on this.

**Comment by Mgamerz** [comment]
This has been fixed in the code currently on Beta branch. Due to failing tests due to another issue there is no nightly for this commit. When the test passes (likely after being fixed tomorrow) it will automatically generate a new nightly with this fixed.

**Comment by henbagle** [comment]
Latest nightly has built.

**Comment by Mgamerz** [comment]
This should be fixed in the latest nightly.
