### ISSUE TITLE
Dialogue Editor ME3 saves with wrongly ordered SpeakerLists on Entries

### ISSUE THREAD

**Issue by linkenski** [Mgamerz/ME3Explorer#302]
**Description**
When editing conversations in ME3 (OT version, possibly LE3 too) the `aSpeakerList` array on Entries gets misarranged, and certain conversations break entirely when this happens, leading to game-breaking bugs.

**To Reproduce**
Attach new nodes to a conversation and save it.

1. To follow a specific example of a conversation that broke on my end, find the conversation "proear_trial_m_dlg" in BioD_ProEar_130Trial_LOC_INT"
2. Go to 'Dialogue Editor'
3. Clone something, and attatch it to a node.
4. Save and compare the `aSpeakerList` in `m_EntryList` Array to that of the vanilla version of the file.

**Expected behavior**
![image](https://user-images.githubusercontent.com/17158981/151669333-f13bac6b-40f3-4d25-891e-7ca67ce0b427.png)

**Version information:**
6.1 05-12-2021

**Other information**
This file was also broken in the past before the GUI overhaul to Dialogue Editor, but I started from scratch with older versions of GUI Dialogue Editor, and only recently had the old bug where the Trial Conversation on Earth doesn't play, after making edits in the latest stable version of the editor. I'm not 100% sure the aSpeakerList was only broken now, and not a relic of the past. However, fact is, I changed something with the latest stable, and now that old issue came up again. Last time it was because certain speaker indexes were wrongly changed upon saving.

**Comment by linkenski** [comment]
Um, so I found maybe the actual issue, but it's relevant too: actors labeled `proear_tribunal` with indexes 2 and 3 (so `proear_tribunal_2` and `proear_tribunal_3`) were saved as new names, without using the index but storing it with the "_" in the name itself. This apparently breaks some conversations.

**Comment by linkenski** [comment]
![image](https://user-images.githubusercontent.com/17158981/151669980-26593a10-831f-42ba-9fbc-fddcd3ba99d6.png)
Found the real issue. These names, that were simply using generic indexes before, have been stored each as new names, loaded individually into the `m_aSpeakerList `of the conversation, and being referred to in the `aSpeakerList`.

This is the exact issue that was described to me by KK when the GUI version got written, and fixed those issues, which means it has resurfaced with changes made more recently. This seems to be an issue of variance in the way dialogues are interpreted in each game, requiring further checks depending on which game's bioconversation class is being handled.

**Comment by Mgamerz** [comment]
This is likely because the backing code is using `string` instead of `NameReference`, which is `string` and `number`. When a dev has some time they'll look into this soon.

**Comment by linkenski** [comment]
Thank you very much!
