### ISSUE TITLE
FaceFX Audio playback only works for FemShep

### ISSUE THREAD

**Issue by linkenski** [Mgamerz/ME3Explorer#306]
**Describe the bug**
If you're on a Male FaceFX it will still play the female audio.

**To Reproduce**
Open dialogue editor, or just FaceFX editor of a LOC_INT file that has the player talking. BioD_Engineering for the nor_adams_d conversation.

1. Open BioD_Nor_405Engineering_LOC_INT with Dialogue Editor
2. Choose "nor_adams_d_dlg"
3. Find a player reply, and go to the "Assets" tab.
4. Click on the mask icon of the Male version to open it in FaceFX Editor.
5. Hit the play button.
6. It should play Female Shepard's line over Male FaceFX data.

**Expected behavior**
It should have played Male Shepard's line over Male FaceFX data.

**Version information:**
6.1 Nightly 10-02-2022
Also present in the prior nightly to this one.

**Stack trace**
If you see an error dialog with a details or copy button, please post the details here. 

**Other information**
I mainly work in Mass Effect 3, and I still work on the OT. If the issue can't be replicated for LE3, it might be a backwards-compatible thing.

**Comment by SirCxyrtyx** [comment]
Fixed. Thanks for the bug report!
