### ISSUE TITLE
Dialogue Dumper ME3 LE

### ISSUE THREAD

**Issue by Inachos** [Mgamerz/ME3Explorer#311]
Hello dear Explorer Devs,

I´ve got a huge problem with the dialogue dumper. I need all the transcripts from ME3 LE in german language, but the dumper only extracts the "Owner" and "Shepard" lines. All of the "hench_***" lines etc. are missing. ME2 Dumping worked very fine. Its only ME3 that is causing problems for me. A User on the discord server tried to help me and was also extracting the Transcripts. She confirmed, that the tool misses certain lines. Can you please look into it? I am trying to create a mod and need the transcripts for doing me plans. 
Your help and work are very much appreciated! Thank you very much ! :)

**Comment by Mgamerz** [comment]
It looks like this is hardcoded to look at LOC_INT. I'll see what I can do to make it configurable.

**Comment by Mgamerz** [comment]
Try the latest nightly. Make sure you have loaded DEU TLKs and select the DEU language in the dialogue dumper.

**Comment by Inachos** [comment]
Hey I just saw your reaction now and tried to the dumper. Seem to work now! Than you very much! :D
