### ISSUE TITLE
BUG: Appending Audio to Any Existing AFC Fails

### ISSUE THREAD

**Issue by SpaceD0lphin** [Mgamerz/ME3Explorer#325]
**BUG:**
When attempting to append audio to a pre-existing AFC (whether custom or vanilla) the file will at first appear to convert as normal, but no audio will play.

**STEPS TO REPRODUCE:**
[AudioReplacementIssue.zip](https://github.com/ME3Tweaks/LegendaryExplorer/files/9055253/AudioReplacementIssue.zip)

1. Open `BioD_Cit001_115Joker_LOC_INT` (Vanilla AFC not included due to filesize, it's `DLC_EXP_Pack003_Base_Int` )
2. On E49 (Str Ref 791385 - "Find him!") attempt to replace the audio with DeadCow.wav
3. Leave options as default, select **Update WwiseEvent Lengths**
4. See file convert, changes occur. File _can be played in editor_, but will _not_ play ingame.
5. Replace the audio again with the same file, this time designating a custom AFC name (`DLC_MOD_TEST`)
6. Audio replaces successfully, can be played in editor and ingame.
7. Replace the audio again, targeting the original existing AFC name again, DLC_EXP_Pack003_Base_Int
8. Observe how the Filename field has not changed away from what it was and Stream shows unsupported or 00:00

**EXPECTED BEHAVIOUR:**
Audio should replace within named AFC as expected.

**WORKAROUND:**
Audio will successfully write and play in-editor and ingame if a new AFC is created each time.

**NOTES ON BEHAVIOUR:**
- If trying to change the target to a different, pre-existing AFC, the WwiseStream list shows the file's length as 00:00 or 'unsupported' post-conversion and audio will not play in editor.
- Targeted pre-existing AFC filesize can be seen to increase and the audio may play in editor, but will not play ingame.

**VERSION INFO:**
9.1 Nightly 04/07/2022

**GAME:**
OT3

**Comment by Mgamerz** [comment]
This should be fixed in the latest nightly.

**Comment by SpaceD0lphin** [comment]
Closing as issue resolved :)
