### ISSUE TITLE
Error loading PS3 package

### ISSUE THREAD

**Issue by mirh** [Mgamerz/ME3Explorer#326]
1. Go to Package Editor
2. Open `USRDIR\BIOGAME\COOKEDPS3\BIOA_NOR10_04_DS1.XXX`
4. See error "LZMA decompression failed"

**Screenshots and files used to replicate this**
I attached the file [here](https://easyupload.io/jep0er) for your convenience. 

**Version information:**
6.1 nightly 11/07/2022 (stable is broken too)

**Comment by mirh** [comment]
It's still not working here.

**Comment by Mgamerz** [comment]
This is fixed in the latest nightly. It was committed for some time but I forgot to merge it into nightly. It should autobuild and be fixed. Not all files work; however our toolset is not designed for non-PC platforms, it is just an extra side feature that it works for them to some degree.
