### ISSUE TITLE
ME1 Audio Transcript extraction bug, german version

### ISSUE THREAD

**Issue by Inachos** [Mgamerz/ME3Explorer#331]
Hi there. I´ve tried to work with ME1 Audio in german language. I extracted everything without any problem and now i only need the german transcript. The Problem is: The german Transcript i try to dump is 100% in english. I am very sure, that i dumped the right file. Very sure ... so i think maybe its a problem for the Tool? 
I would be very gratefull if someone could take a look into it, please. :)

Anyway. Thank you very much! Every kind of help is appreciated alot! :D

**Comment by Mgamerz** [comment]
Is this ME1 or LE1? When you say you 'dump' text, what does that mean? Please follow the template.

**Comment by mirh** [comment]
If I tell to dialogue dumper to extract ME1 in italian, I get the english lines. 
If I tell to dialogue dumper to extract any language in LE1, I get a 24KB excel file with just one line. 
If I tell to dialogue dumper to extract ME2 in italian, I get a 64KB excel file with just a few of lines (though that could be partly justified by having installed the thing in english from origin)

**Comment by Mgamerz** [comment]
This should be fixed for game 1 in the latest nightly. There was some changes needed to how Game 1's local TLKs are loaded and scoped to a specific language.

**Comment by mirh** [comment]
LE1 seems fine. ME1 somehow just gives me 48 `nor20_empty_locker_dlg` lines (in the right language at least) and then nothing else.
