### ISSUE TITLE
Feature: Make editing PowerCustomActionClasses easier

### ISSUE THREAD

**Issue by levicki** [Mgamerz/ME3Explorer#332]
Remapping powers is a bit tedious right now.

I am referring particularily to this part:

![image](https://user-images.githubusercontent.com/16415478/183263196-f43f8cdc-8e30-491f-b9a7-c8cc6dc9ac4f.png)

You need to look up the power ID and set it in the right index by typing in a name.

But all those powers (their indices) are actually defined in an enum in SFXGame.pcc file:

![image](https://user-images.githubusercontent.com/16415478/183263247-d5404b65-7244-48a7-9ee6-814c708e9d50.png)

So I was thinking how it would be nice to be able for those entries to be updated automatically when a power is recursively cloned into the file.

It is not like you can (or should even try to) set wrong powers to wrong indices in `PowerCustomActionClasses` array anyway because they wouldn't work, not to mention that the array should be protected from adding and removing entries since it has to have 101 items.

Just some food for thought, nothing urgent or required.

**Comment by Mgamerz** [comment]
You can assign any power custom action id. It is simply the index. For compilation purposes this is not required, you can change it to whatever you want. In some of my private work I've added power and as long as they don't overlap other added powers and are in the correct slot it is fine. The array also doesn't need 101 entries, it is done by integer index, not enum.

**Comment by levicki** [comment]
@Mgamerz I see, I remember reading somewhere that you should not delete items (for example Unity has to be at index 100).

What I meant is that if I import SFXPower_Overload for example and it gets index 13264 that said index gets set into Item 28 in this array without me having to do it because the editor can know that's the right position based on the enum.

Granted, it's not a big deal, just an idea.

**Comment by SirCxyrtyx** [comment]
"Magic" edits to existing objects when cloning in other objects is not something we're going to do for such a niche scenario. This sort of thing violates the principle of least surprise.

**Comment by Mgamerz** [comment]
> What I meant is that if I import SFXPower_Overload for example and it gets index 13264 that said index gets set into Item 28 in this array without me having to do it because the editor can know that's the right position based on the enum.

This would be better suited for a standalone tool rather than in a general purpose editor.

**Comment by levicki** [comment]
@SirCxyrtyx 

> This sort of thing violates the principle of least surprise.

There are some other things that violate that same principle, but I will report them in separate issues.

@Mgamerz 

> This would be better suited for a standalone tool rather than in a general purpose editor.

Like it or not I have to agree with you on that one. Some tool for class power customization would be nice. Maybe I will look into it when time allows.

**Comment by Mgamerz** [comment]
I've wanted to do one since I worked on ME2Randomizer. Just haven't had the time and when I do have time it's because I'm burned out and taking a break. Would definitely be willing to consult on it though. I know how they work for 2 and 3.

**Comment by levicki** [comment]
@Mgamerz I understand the burnout part, people get tired of things they find interesting once those things become a chore.

As for consulting I wonder if there is a way to unpack the whole pcc and decompile it fully into scripts, apply patch via diff and then recompile and repack? Or perhaps a way to script changes to pcc files instead of doing it in the editor by hand?

I have a bunch of other questions about how some things work and where they are located, but I try to use Discord modding_dev_help sparingly.

**Comment by Mgamerz** [comment]
This could all be automated via a UI. I would build a single package file with all powers in it (for performance), then have the tool port the power class into the destination package, and have it adjust the properties to hook it up. I wouldn't edit the scripts since it'd be done through automation and editing scripts is typically done by hand, and powers are done by properties.

This can all be done via Legendary Explorer Core. It's the backend of LEX. I did it in ME2Randomizer and I've also done it for 3 in one of my unreleased projects (it is not a power editor though).

**Comment by levicki** [comment]
The reason I mentioned editing scripts is that I found it easier to do bulk search / replace to also hook auto level up for replaced powers.
