### ISSUE TITLE
Net 5 is end of life.

### ISSUE THREAD

**Issue by thunderpants** [Mgamerz/ME3Explorer#334]
LegendaryExplorer complains about Net 5 not been installed but i removed it and installed Net 6 due to it reaching end of life.

Microsoft says:
This release [Net 5] has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as [.NET 6.0](https://dotnet.microsoft.com/en-us/download/dotnet/6.0).

Is it wise/ok  to continue using Net 5 ?

**Comment by Mgamerz** [comment]
Yes it's fine. We don't use network features in LEX. Nightly uses .NET 6.

**Comment by Mgamerz** [comment]
LEX Stable now uses .NET 6.
