### ISSUE TITLE
TLK manager gets stuck if ME1 folder contains LExplorer

### ISSUE THREAD

**Issue by mirh** [Mgamerz/ME3Explorer#335]
**To Reproduce**
1. Extract legendaryexplorer in some folder inside your ME1 install folder
2. Open TLK manager
3. Scan ME1
4. Even after 10 minutes, the progress bar is still looping. 

**Expected behavior**
Don't hang. 

**Version information:**
6.2 nightly 12/08/2022

**Other information**
This doesn't seem to happen with ME2, even though the tlks inside the *DLC_MOD_Interop* folders still gets scanned and added.

**Comment by Mgamerz** [comment]
This is not a supported configuration. Putting any modding tools inside of the game directories is prone to breaking all sorts of things. This is not a bug; this is the user choosing a bad location to put it - we are not going to make a blacklist since it would be simply too much work to maintain.

**Comment by mirh** [comment]
It's not that it has to be "supported", and I wasn't really asking for a blacklist (hardcoding stuff sounds awful indeed). 
Just *somehow* for the thing not to halt and catch fire. 

I don't know then the specific reasons for (I guess) the presence of the *`DLC_MOD_Interop`* folders, but even without any awareness of its logics that breaks I can still think of many workarounds. 
For instance, you could ship them inside zips (just like you already do with the wwise templates). And/or you could have LExp exclude from every scan its own directory.
