### ISSUE TITLE
Feature: Automatically remove trashed entries from ClientDestroyedActorContent and TextureToInstancesMap

### ISSUE THREAD

**Issue by rondeeno** [Mgamerz/ME3Explorer#353]
**Is your feature request related to a problem? Please describe.**
When trashing entries that are referenced in the ClientDestroyedActorContent array in BioWorldInfo or the TextureToInstancesMap in PersistentLevel, it's pretty tedious to have to manually remove each reference from those lists, especially the TextureToInstancesMap since entries can only be removed from it through hex editing.

**Describe the solution you'd like**
It would be nice if entries were automatically removed from the ClientDestroyedActorContent array and the TextureToInstancesMap upon being trashed, similar to how entries are automatically removed from the Level Actors array in PersistentLevel. It would also be convenient if the trash warning was prevented from appearing if the ClientDestroyedActorContent array or the TextureToInstancesMap were the only places that reference the entry.

**Describe alternatives you've considered**
I've been removing them manually, which is tedious and takes up some time if many entries have been trashed.

**Additional context**
N/A

**Comment by Mgamerz** [comment]
This has been implemented into the latest nightly.
