### ISSUE TITLE
Dialogue Editor unchecks "Default Reply" and "Major Decision" when clicking twice on reply nodes.

### ISSUE THREAD

**Issue by Lunkensko** [Mgamerz/ME3Explorer#362]
**Description of bug**
In Dialogue Editor, if you have currently selected a player dialogue node in the GUI (corresponds to m_ReplyList array) and click once more, the two boolean values "bIsDefaultAction" and "bIsMajorDecision" (In the the GUI: "GUI-Control" -> "Default Reply" & "Major Choice") are both set false.

**To Reproduce**
You must open a dialogue in the Dialogue Editor, and select a player line (Reply) that already has "Default Action" and "Major Decision" set as true in GUI-Control. Then re-select the same Reply by clicking on it again, and they will now be false due to a bug. It also occurs in the actual data, the "m_ReplyList" array, after this behavior occurs.

1. Open any "LOC_XXX.pcc" file in Dialogue Editor
2. Select a conversation in the list in the lower-left.
3. Click on one of the grey "Reply" nodes. and open GUI-Control in the rightmost view.
4. Note that the GUI Control tab has "Default Action" and "Major Choice" ticked true. If they don't, keep searching for a node that has it.
5. Once you've found one, also check the "m_ReplyList" array for the corresponding index matching the Reply node. In here, check that "bIsDefaultAction" and "bIsMajorDecision" are set to true.
6. Now click once more on the Reply node you already selected in the GUI.
7. The Default Action and Major Decision tickboxes have been unticked. In the array, they will now also be set to false.

**Expected behavior**
Double clicking or re-clicking an already selected node should not be unticking the boxes or setting the array element properties to false.

**Version information:**
LEX 6.3 Nightly: 12-02-2023
*Past versions of LEX have always done this, even Stable.

**Other information**
Has been reproduced in LE3 as well as ME3.

**Comment by SirCxyrtyx** [comment]
This is fixed in the latest nightly. Sorry this took so long!
