### ISSUE TITLE
Console key keybinder Yes / No prompt is inverted

### ISSUE THREAD

**Issue by levicki** [Mgamerz/ME3Explorer#366]
@Mgamerz 

Tested in the latest version of ME3Tweaks Mod MAnager.

Console key keybinder message box warning you there is no game backup has its Yes / No actions inverted.

Clicking Yes doesn't do anything, clicking No proceeds to wait for a keypress to assign a new key.

Furthermore, there's no option to just clear existing key(s) -- that would be handly (I use Tab to reload when playing).

I might have mentioned this on Discord but forgot to create an issue for it here.

**Comment by levicki** [comment]
This happens for all Change mini key buttons, not for other buttons.

**Comment by Mgamerz** [comment]
This repository is for Legendary Explorer.

**Comment by levicki** [comment]
I am so sorry man... I am dumb today. Is there a way to move the issue over?

**Comment by levicki** [comment]
Actually I reported it there already and you said it was fixed. I added a comment now stating it isn't fixed fully.
