### ISSUE TITLE
Feature Request: Debug Menu option to check for script compiler warnings or errors

### ISSUE THREAD

**Issue by Knighthawk1895** [Mgamerz/ME3Explorer#369]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to debug a crash issue with an unknown cause. There's several checks that can always be performed in an effort to prevent these types of crashes like checking for bad references, broken materials, and duplicate indices. One thing we currently do not have a tool for is a check on functions to see if the script compiler has registered any warnings or errors. This can be accomplished by checking the class exports one by one and occasionally will be flagged by DebugLogger but the ability to have a list of functions with these kinds of issues at a glance would be immensely helpful.

**Describe the solution you'd like**
An option similar to checking bad references, broken materials, and duplicate indices that will provide a pop up with a list of functions the script compiler has flagged with warnings or errors.

**Describe alternatives you've considered**
The classes themselves could also be flagged, that would still be useful in a file with ton of classes like SFXGame, Engine, or the startup file I've created.

**Additional context**
This is what my startup file currently looks like, I can go through all these classes one by one to check to see if an edit I made to one function caused issues with another or if there's a warning tha might actually produce a crash. But it would be useful to just have a list of functions to check.
![startupfile](https://user-images.githubusercontent.com/95185489/226214197-4526e3fc-0c62-44a4-91af-5a150c408ac2.PNG)

**Comment by SirCxyrtyx** [comment]
Feature added in e1e292183cf3801ab7123eb1b1ffa04dc7e734ba
