### ISSUE TITLE
Feature: Add New Blank FXA Within an AnimSet

### ISSUE THREAD

**Issue by SpaceD0lphin** [Mgamerz/ME3Explorer#373]
**Is your feature request related to a problem? Please describe.**
When creating non-vocal animations (for reaction shots, etc) the animator relies upon a `NonSpkr FaceFX AnimSet`. Every conversation has one of these, but most do not have any lines in them. Currently, the easiest way to create a new FaceFX animation is by cloning an existing one and changing details; however, there is no easy way to create a new animation if one does not already exist.

An example of a conversation with a blank `NonSpkr`:
![image](https://user-images.githubusercontent.com/79815367/231279733-14c53998-20b8-4ed5-8ba2-b8b6a1af03f6.png)

An example of a NonSpkr in a different conversation within the same package.
![image](https://user-images.githubusercontent.com/79815367/231280310-e59b556c-1b3d-46fe-b9ca-bb04ff1ceca9.png)

**Describe the solution you'd like**
The option to "**Add New**" would be very useful.

**Additional context**
In order to work properly, a `NonSpkr` FaceFX animation line should always have an Index of -1.
Its Path should always be blank.
Its ID should always be blank.

But, if the FaceFXAnimSet is _anything_ other than a `NonSpkr`, then a newly created line should also add to the array found in its Properties, under `ReferencedSoundCues`.
Its Path should always be the same as whatever export it references in the array.
Its ID should always be the String Ref number. The String Ref number it needs can be found in the line's Name. If the animation's name is `FXA_628859_M`, then the ID will be 628859.

So, upon 'Add New', a dialogue could check for whether the AnimSet you're trying to add to is a `NonSpkr` or not.
If not, ask for an export number and a name.
From that export it can glean the path, and from the name it can get the ID.

If it is a NonSpkr, just ask for a name.

**Comment by Exkywor** [comment]
I wrote something similar for what's needed on the backend of this, so I can try giving it a shot.
