### ISSUE TITLE
xml cannot be imported to LE1

### ISSUE THREAD

**Issue by Vojtak42** [Mgamerz/ME3Explorer#380]
# Please fill out the following form *in its entirety*. 
The more information you provide, the easier it will be for us to reproduce the issue.

**Describe the bug**
.xml files cannot be imported to LE1 through tlk manager.

**To Reproduce**
Export xml file (i named it "tlk M") from LE1 (GlobalTLK_tlk_M) through tlk manager, edit it and try to import it, it will do nothing.

**Expected behavior**
importing tlk xml files

**Screenshots and files used to replicate this**
no need

**Version information:**
6.2 14.09.2022

**Comment by Mgamerz** [comment]
Without the file you are attempting to import, we will not work on this. Follow the template. There is not enough information here to reproduce your specific issue.

**Comment by Vojtak42** [comment]
I understood it, that i should specific the name of file😅. I will send it later. 
And i think there is enough information. The tlk file in .pcc just doesn't change after clicking on import, no matter what change you made to it.
