### ISSUE TITLE
feature request: gltf mesh export

### ISSUE THREAD

**Issue by Padme4000** [Mgamerz/ME3Explorer#381]
**Describe the solution you'd like**
To be able to export meshes in the gtlf format. Umodel has another option to export meshes in the gtlf format. The good thing about this format mesh normals are not lost as PSK sadly does not support storing normals.

**Comment by Mgamerz** [comment]
Is this a recent thing in umodel (last few years)?

**Comment by Mgamerz** [comment]
This is implemented in the current nightly that is building.
