### ISSUE TITLE
at least two images from the Asset Database wiki page are broken

### ISSUE THREAD

**Issue by modusc896d352** [Mgamerz/ME3Explorer#398]
title should be self-explantory, but anyway...

there is a page on the wiki surrounding [how Asset Database works](https://github.com/ME3Tweaks/LegendaryExplorer/wiki/Finding-in-game-assets-quickly-%28Asset-Database%29). though said page is relatively well-written for the most part, only two images show up broken.

they can be found in the following order:
- on the paragraph above "Meshes Tab".
- on the paragraph above "Textures Tab"

i *may* fix this issue myself if no one else is up to the task but to do i would have to take a new screenshot of like two tabs *at a minimum*, so don't count on me for this one.

**Comment by modusc896d352** [comment]
also, minor UI quibble but virtually all tabs beyond "Files" and "Lines" don't have much in the way of sorting utilities without having to rely on the "Filter" tab. i may have to open a separate issue for that, but for now, i'll see what i can do with these broken images.

one question i would like to ask is when taking a screenshot of the Asset Database, do i have to show like the ME3 database to be in line with the other images shown in that page or can that database be any game i want? i only have ME1 installed at the moment and i generated that game's database fairly recently (about 3 minutes) so i wonder if it's fine to just show ADB with ME1 in it or if it's off-limits or something.

**Comment by Mgamerz** [comment]
For the wiki, as long as you aren't following steps in a guide, you can use pretty much any image. For this I don't think it's a guide so you can use any screenshot from a game.

**Comment by modusc896d352** [comment]
ok, i'll do some messing around with the ADB and see how this whole "image" thing turns out.

my strategy here is to provide a suitable replacement for the two broken images so for the new images i'll just aim for ME3 just to be safe.

**Comment by henbagle** [comment]
Fixed with most recent update to ADB wiki page.

**Comment by Mgamerz** [comment]
Would be good to add a link to this page to AssetDB. Perhaps in a menu
item. We do this for package editor in the opening screen.

**Comment by henbagle** [comment]
AssetDB doesn't have the welcome screen like the rest of the editors do, as it opens directly into the most recently used database.

How about a "Help" menu that contains a link to the guide?
