### ISSUE TITLE
Soundplorer not updating WwiseEvents

### ISSUE THREAD

**Issue by ghost** [Mgamerz/ME3Explorer#400]
Soundplorer does not always update WwiseEvents when replacing audio, even if you tick the box to do so.

**To Reproduce**
1. Find a LOC file to test on, it requires dialogue in it but that's easy to find via asset database
2. Click on a line of dialogue
3. Click Replace
4. Pick the .wav file you want to replace the audio with
5. tick Update Event Lengths
6. Rename destination AFC to whatever you want it to be
7. Open file in Package Editor, and more often than not you'll find the corresponding WwiseEvent has not changed or has reverted to 0

**Expected behavior**
The WwiseEvent durationseconds for both M & F updates to the exact duration of the imported audio

**Version information:**
Stable & Nightly

**Comment by Mgamerz** [comment]
Can you provide sample files and exact steps? Which specific file? What exports?

**Comment by ghost** [comment]
I tried uploading an audio file here but GitHub wouldn't let me select them, basically any dialogue file extracted from LE3 can be used for this. This is happening with any audio I try uploading, so I'll give some example files to use:

1) Open **BioD_CitHub_EmbassyP1_LOC_INT.pcc** and **BioD_CitHub_EmbassyP3_LOC_INT.pcc** in Package Editor
2) Go to EmbassyP3 and select **export 1581 citprs_samara_d_D**. Drag and drop it into P1_LOC_INT, clone all
3) Open P1_LOC_INT in Soundplorer
4) Scroll down to find a dialogue file with **global_samara** in the name
5) Select it, then click on Replace and choose the .wav file you want to import
6) Set **Sample Rate to 44100**, and tick **Update Event Lengths**
7) Add a new name for the **Destination AFC** and finish replacing
8) Go back to P1_LOC_INT in Package Editor
9) Go to the export for **citprs_samara_d_D** and look for the WwiseEvents for the line you replaced. There will be two - one for F and one for M.
10) These will either not have changed (a bug), set their DurationSeconds to 0 (a bug), or if you're really lucky it will have worked and it will set the length of the line to be the same as the new imported dialogue
11) If it hasn't worked, sometimes replacing a second time makes it work, but that only happens sporadically

What it should do is update the DurationSeconds to exactly match the audio you have replaced. This very rarely happens correctly.

**Comment by henbagle** [comment]
I'm pretty sure I just fixed this, it was a weird subtle bug when changing what AFC the stream was stored in while importing. I had a hard time reproducing it but I did figure it out. 

Let me know if the latest nightly fixes the issue!
