### ISSUE TITLE
Some meshes are not exporting in UDK format correctly

### ISSUE THREAD

**Issue by vegz** [Mgamerz/ME3Explorer#402]
**Describe the bug**
I am trying to export some meshes from ME2 into UDK. Most of the meshes are working fine but for some reason, some are not showing up correctly. I have tried psk, udk, and importing it from blender but same result. It seems LEX is exporting some meshes wrong for some reason.

**To Reproduce**
1. Open BioP_CitHub in Package Editor (LE2)
2. Go to exports 11520 (Neon_Foor_Edge_Divide) and 11534 (Neon_Wall_1x4). Open them in mesh explorer and then export in udk format. 
3. Open UDK and press "open an external package" on each files you made before.
4. Neon_Foor_Edge_Divide is missing its triangles/verticies while Neon_Wall_1x4 is not.

**Expected behavior**
The triangles and data of certain meshes would be exported with the UDK file.

**Version information:**
6.3 Nightly 1/9/2024

**Stack trace**
N/A

**Other information**
N/A

**Comment by SirCxyrtyx** [comment]
Oddly enough, this seems to be an issue with the mesh, not the export process. This is the Elements array on the problem mesh: 
![image](https://github.com/ME3Tweaks/LegendaryExplorer/assets/5533111/fdd06141-8d3e-41fb-ad56-96328fb13073)

Note that the Material Index is 2, despite their only being 2 materials (so the only indexes ought to be 0 or 1). This is exported as-is, which evidently causes trouble for UDK. Changing that to 1 causes the tris to show up in UDK.
