### ISSUE TITLE
Saving PlotManagerAutoDLC file after editing BiOCodexMap breaks the file

### ISSUE THREAD

**Issue by vegz** [Mgamerz/ME3Explorer#403]
**Describe the bug**
Editing the BioCodexMap in any LE1 DLC or DLC mod will cause the game to not go past startup. 

**To Reproduce**
1. Open PlotManagerAuoDLC_UNC (LE1) in Plot Editor
2. Go to Codex Map and delete a page or a section from it
3. Save the file
4. Start up LE1, game will crash upon entry to main menu

**Expected behavior**
Saving the file changes the BioCodexMap correctly

**Screenshots and files used to replicate this**
PlotManagerAutoDLC_UNC (LE1)

**Version information:**
6.3 Debug/Nightly 1/15/2024

**Stack trace**
N/A

**Other information**
N/A

**Comment by henbagle** [comment]
Pretty sure this should be fixed now. Should also fix a very similar bug when adding a new codex page to LE1, which before would have created a malformed entry.

It's a duct tape fix, plot editor ideally needs a rewrite.
