### ISSUE TITLE
Saving BIOC_Materials after editing in Plot Editor causes game to hang on Startup

### ISSUE THREAD

**Issue by vegz** [Mgamerz/ME3Explorer#404]
**Describe the bug**
Editing this file in plot editor for LE1 causes the game to hang in the main menu. This is inconvenient considering all of LE1s codex, quest, and boolean data are in that file.

**To Reproduce**
1. Open BIOC_Materials in Plot Editor
2.  Delete/Change anything 
3.  Save the file
4. Open LE1 and game will then hang in the manu

**Expected behavior**
BIOC_Materials can be edited without causing the game to hang.

**Screenshots and files used to replicate this**
BIOC_Materials (LE1)

**Version information:**
6.3 Nightly/Debug 1/15/2024

**Stack trace**
N/A

**Other information**
N/A

**Comment by henbagle** [comment]
Can you check for me if the latest nightly with the fix to #403 fixes this same issue? I'm not currently experiencing this hang after editing the codex, quest, and state event map with the latest changes.

**Comment by vegz** [comment]
It appears to have been fixed with that. Thanks!
