### ISSUE TITLE
(LE2) Can't replace AFC Entries in Soundplorer

### ISSUE THREAD

**Issue by Dimenarius** [Mgamerz/ME3Explorer#411]
In order to replace audio for LE2, Wwise 7110 x64 should be installed like mentioned in the Welcome Screen for Soundplorer.

I have set the path to the WwiseCLI.exe of 7110 in Soundplorer.

Path = C:\Program Files (x86)\Audiokinetic\Wwise 2019.1.6.7110\Authoring\x64\Release\bin\WwiseCLI.exe

However the "Replace" button remains greyed out, when selecting AFC Entries within an AFC File.

Is this meant to happen?  

**To Reproduce**

1. Open Sound Explorer from the Legendary Explorer Nightly Audio Tools
2. Click on Wwise/Set Wwise Executable Paths
3. Enter path to WWiseCLI.exe for Version 7110 x64 and click "Set Paths"
4. Open any AFC File from LE2's game files (in this example endgm1_arrival_c_s_Int.afc from LE2 Base Game Files)
5. Replace-Button is greyed out, when selecting AFC Entry.

**Expected behavior**

I should be able to replace the AFC Entries with new WAV Files as promised with all the requirements met.

**Screenshots and files used to replicate this**
![image](https://github.com/ME3Tweaks/LegendaryExplorer/assets/30260206/372e0969-84c7-4a91-af10-4413fb364166)
![image](https://github.com/ME3Tweaks/LegendaryExplorer/assets/30260206/f67dae44-e252-41d4-ad5f-e777c995d12f)
![image](https://github.com/ME3Tweaks/LegendaryExplorer/assets/30260206/4de61705-3d0e-453f-95ae-89ba909b3f0c)

**Version Information:**

Legendary Explorer 6.3 Nightly 29.04.2024 is being used.

The steps were also attempted with the stable version without success.

**Other information**

I installed Wwise 2019.1.6.7110 x64 through the Audiokinetic Launcher.

Maybe this Wwise Version has to installed outside of the Program Files(x86) Folder because of permission issues? However running the tool as admin also didn't work so maybe this isn't the problem.

Is something else besides WWise missing to make the Replace-Function work? I installed the .NET 7 Runtine in order to use the Nightly Legendary Explorer.

**Comment by henbagle** [comment]
The AFC is an audio cache on disk that is referenced by offset into the file. Directly replacing entries in an AFC would break all of the rest of the references in the bank. AFC browsing in the toolset is for export and listening only.

You need to replace audio by locating the WwiseStream export in the package files where the audio is referenced, and replacing from there, which will put your new audio into it's own AFC.

The replace tooltip has been updated in 74741cd to reflect why audio replacement is not possible.
