### ISSUE TITLE
Feature Request: UScript Importer

### ISSUE THREAD

**Issue by AudemusN7** [Mgamerz/ME3Explorer#415]
**Is your feature request related to a problem? Please describe.**
In package editor, making bulk edits to a file is always an extremely time consuming process. Since the introduction of the Script Editor tab this problem has been greatly reduced, but there are still instances where you can spend hours copy/pasting changed values to hundreds if not thousands of exports. For example, changing light properties inside of one of LE1's UNC prefabs requires editing a couple of hundred prefrab lights, and then often a few hundred more in the StaticLightCollectionActors.

**Describe the solution you'd like**
My idea for the solution to this is to essentially introduce a reverse of Package Dumper. Packages can be dumped to a text file where bulk edits can be made with Notepad++ or a python script, and then reimported. Given the potential complexity of this I'm NOT suggesting a tool that can effectively build entire package files from text, but rather a utility that can look for differences in things like Properties and Names and make those bulk changes without having to do it manually inside LEX's interface.

![Notepad_cFpaggkZf9](https://github.com/ME3Tweaks/LegendaryExplorer/assets/44449267/dffc5f3a-b829-4a42-a4cb-cedbdb7e523d)
In the above example, if I wanted to change all if the lights in the package that use these values, I can just do a simple find + replace.

**Describe alternatives you've considered**
I've been asking Exkywor for help with a lot of smaller experiments to help automate tasks, and most of them (with the exception of binary related experiments like 1D lightmaps) could all be achieved through this proposed feature request. Since it's so robust, it can effectively handle the automation of any tedious task involving names or properties without having to program a custom solution for smaller use cases.

**Comment by Mgamerz** [comment]
Next nightly should have a way to dump all uscript from package in my experiments menu. This will not help you edit things in collections though.

There is a compile experiment menu item but it does nothing yet as it will be more complicated. Additionally, if the package being worked on has duplicate objects with same instanced full path (a few files in vanilla do) this will probably break the file.

**Comment by SirCxyrtyx** [comment]
I think this should be limited to non-script exports (where the “UScript” is just a properties block). It sounds like that would be sufficient for the feature request, and property recompilation is never going to break anything (unlike script recomp unfortunately).

**Comment by SirCxyrtyx** [comment]
I’ve got a working prototype of this feature, but testing it has turned up a bunch of compilation bugs. I should have this done in a couple of days.
